---
title: "Action People-1.1: Engagement Plan"
---

::: callout-note
## Full Action Statement

Develop and implement the NBEP Engagement Plan to convene and activate partners to implement priority CCMP actions.
:::

## Action Description and Statement of Need

This Action will develop a coordinated and collaborative NBEP Engagement Plan to guide NBEP’s convening services and partnership-building activities. The Engagement Plan will include work to articulate and promote a unique identity for the Narragansett Bay region that highlights specific CCMP implementation opportunities and challenges within the broader southern New England context (see Finance Plan Action: [People-3.1](action_3_1.qmd)).

Successful implementation of the NBEP CCMP requires an informed, engaged, and empowered community of partners making choices and taking actions that increase environmental health and resilience. Coproduction of knowledge and management solutions can build trust among resource users and managers and provide deeper understandings and diverse perspectives about what the people of the Narragansett Bay region value most about the environment. NBEP seeks to energize effective partnerships to implement CCMP actions and develop a strategic framework of networks and services to support partner needs for targeted engagement throughout the watershed.

NBEP will lead the development and regular update of the Engagement Plan to describe, prioritize, coordinate, and drive NBEP’s convening, outreach, education, and communication activities necessary to implement the CCMP and promote a unique regional identity. The Engagement Plan will guide meaningful collaboration with people and communities most impacted by pressing environmental issues, such as nonprofits, tribes, municipalities, academic researchers, community leaders, businesses, and more. It will also facilitate delivery of responsive, research-based outreach programs focused on priority topics.

The Engagement Plan will coordinate and amplify ongoing efforts and identify opportunities and gaps that can be met by existing or new programs and funding mechanisms. It will also broaden engagement approaches historically limited by organizational or political boundaries to address issues at environmentally meaningful watershed scales. The Engagement Plan will prioritize, focus, and empower engagement efforts to optimize collaboration and support for implementing CCMP objectives and actions. This coordinated approach will inspire new collaborations among existing programs, reinforce existing partnerships, and optimize messaging effectiveness.

Implementing the Engagement Plan requires NBEP to continue hosting quarterly Executive and Steering Committee meetings, biannual Science Advisory Committee meetings, and subject-specific subcommittees and working groups as needed. NBEP will also host topic-specific events, including the Annual Science Event, and offer convening services for partner-led workshops, committees, or meetings to implement partner strategic plans, workplans, or equivalent planning documents that align with the CCMP and the Engagement Plan. NBEP will regularly update the Engagement Plan to adapt to changing conditions in the environment and needs of the people in the region.

## Potential Projects

-   Convene NBEP partners and other organizations to advance connections, knowledge, and solutions at local and regional scales.

-   Convene partners to inventory and coordinate needs for education and outreach programs.

-   Convene partners to explore avenues to establish and promote a unique identity for the Narragansett Bay region to support funding requests and public engagement.

-   Conduct NBEP Science Events.

-   Review existing local and state plans (*e.g.,* Wildlife Action Plans, Nonpoint Source Pollution Management Plans) and compile lists of recommended policy topics that have potential for bi-state or interjurisdictional interest; then, obtain Steering Committee consensus on priority topics, next steps, and appropriate outputs.

-   Establish a regular schedule of communications with elected and appointed leaders at local, state, and federal levels to share NBEP and partner activities, accomplishments, and benefits.

## Outputs

-   NBEP Engagement Plan and regular updates

-   Annual funding opportunities intended specifically for watershed outreach and education that implement the CCMP in the Narragansett Bay region

-   Events to promote engagement with priority science, preservation, and restoration issues and opportunities

-   Working group meetings

-   Reports on select policy topics

## Outcomes

-   NBEP decisions, services, and projects that are responsive to current needs

-   Improved partner coordination for CCMP implementation at various scales (*e.g.,* watershed, state, interstate)

-   Increased NBEP and partner ownership of progress toward CCMP goals and objectives

-   Public support for and participation in CCMP implementation

-   Adoption of policy changes that advance CCMP goals and objectives

## Indicators

All indicators

## NBEP role

Convene, Fund capacity and projects

## Implementing Partners

Steering Committee, other agencies and non-governmental organizations

## Location

Narragansett Bay region, with priority areas to be determined during development and biannual update of the Engagement Plan

## Timeline for initiation

Ongoing

## Estimated costs/potential funding sources

\$1M–5M (NBEP staff time to develop Engagement Plan; annual RFPs for outreach and education activities)

NBEP 320/SNEP; NOAA B-WET, EPA, private foundations
