project:
  title: "2026 CCMP"
  type: website

website:
  title: "NBEP 2026 CCMP"
  page-navigation: true
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        menu:
          - docs/preface.qmd
          - docs/about_region.qmd
          - docs/about_nbep.qmd
          - docs/about_ccmp.qmd
      - text: "Action Plans"
        menu:
          - docs/people_action_plan.qmd
      - text: "Appendices"
        menu:
          - docs/acronyms.qmd
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - text: "Home"
        href: index.qmd
      - docs/preface.qmd
      - section: "About"
        contents:
        - docs/about_region.qmd
        - docs/about_nbep.qmd
        - docs/about_ccmp.qmd
      - section: "People Ready to Act"
        contents:
        - docs/people_action_plan.qmd
        - auto: "docs/people/*"
      - section: "Water Quality Improvement"
        contents:
        - docs/water_action_plan.qmd
        - auto: "docs/water/*"
      - section: "Habitat Protection and Restoration"
        contents:
        - docs/habitat_action_plan.qmd
        - auto: "docs/habitat/*"
      - text: "Public Spaces Accessible to All Action Plan"
      - docs/acronyms.qmd
      - text: "References"
      - text: "Appendices"

format:
  html:
    toc: true
    toc-depth: 2
    code-overflow: wrap
    link-external-icon: true
    link-external-newwindow: true

editor: visual
