project:
  title: "2026 CCMP"
  type: website

execute:
  freeze: auto

bibliography: references.bib

website:
  title: "NBEP 2026 CCMP"
  site-url: "https://nbep.github.io/CCMP2026"
  page-navigation: true
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - text: "Home"
        href: docs/index.qmd
      - section: "About"
        contents:
        - docs/about_region.qmd
        - docs/about_nbep.qmd
        - docs/about_ccmp.qmd
      - section: "People Ready to Act"
        contents:
        - docs/people_action_plan.qmd
        - auto: "docs/people/*"
      - section: "Water Quality Improvement"
        contents:
        - docs/water_action_plan.qmd
        - auto: "docs/water/*"
      - section: "Habitat Protection and Restoration"
        contents:
        - docs/habitat_action_plan.qmd
        - auto: "docs/habitat/*"
      - section: "Public Spaces Accessible to All"
        contents:
        - docs/public_spaces_action_plan.qmd
        - auto: "docs/public_spaces/*"
      - docs/acronyms.qmd
      - section: "Appendices"
        contents: docs/appendix/*

format:
  html:
    toc: true
    toc-depth: 2
    code-overflow: wrap
    link-external-icon: true
    link-external-newwindow: true

editor: visual
