project:
  title: "2026 CCMP"
  type: website

website:
  title: "NBEP 2026 CCMP"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Home"
        href: index.qmd
      - text: "Preface"
        href: docs/preface.qmd
      - text: "About the Narragansett Bay Region"
        href: docs/about_region.qmd
      - text: "About NBEP"
        href: docs/about_nbep.qmd
      - text: "About the CCMP Vision and Strategy"
        href: docs/about_ccmp.qmd
      - section: "People Ready to Act"
        contents: docs/people/*
      - text: "Water Quality Improvement Action Plan"
      - text: "Habitat Protection and Restoration Action Plan"
      - text: "Public Spaces Accessible to All Action Plan"
      - text: "Acronyms"
      - text: "References"
      - text: "Appendices"

format:
  html:
    toc: true
    toc-depth: 2
    code-overflow: wrap
    link-external-icon: true
    link-external-newwindow: true

editor: visual
