---
title: "Action Public Spaces-1.3: Public Access Managemen"
---

Full Action Statement: Support long-term management and stewardship of public access points through community engagement, policy change, and job creation.

# Action Description and Statement of Need

This Action will increase capacity for sustainable management of public access facilities, while improving user experience and accessibility for public enjoyment of the region’s natural areas. Target solutions include enhanced volunteer engagement, innovative funding solutions, and workforce development.

Inequities exist across the region in ease of access to high quality nature experiences [@twichell2022]. Site quality factors such as safety, trash, and perceived water quality conditions impact visitor preferences. Beyond routine maintenance, many access points need upgraded infrastructure and amenities to equitably serve visitors and protect the environment. Such upgrades may include parking areas (especially for waterway access points), multilingual signage, Americans with Disabilities (ADA) trails and boat facilities, trash and recycling bins, and restrooms.

A variety of federal, state, municipal, and non-governmental organizations own and manage various public access facilities such as trails, boat launches, campgrounds, beaches, playgrounds, and urban parks. Taxes, entry fees, non-profit memberships, and donations are typical income sources used for maintenance. However, competing needs for limited funds can result in deferred maintenance (NPS 2022), resulting in reduced visitor enjoyment that leads to reduced visitation and revenue. One-time capital grants for park improvements often do not include funding for long-term maintenance. Innovative funding strategies could be pursued to create sustainable funding streams for operation and maintenance to stay ahead of deferred maintenance (Cohen 2015).

Volunteers often provide in-kind stewardship services and develop a sense of ownership of a particular place. To help build further capacity for community-based management support, non-governmental organizations have created workforce training programs like Groundwork Southcoast’s Green Team and the Woonasquatucket River Watershed Council’s River Rangers to maintain and support ongoing projects and natural spaces.

NBEP will fund capacity to develop robust volunteer recruitment and training, as well as workforce training, for parks and recreation management. NBEP will voice support for development of new policies that support sustainable funding for maintenance and operations.

# Potential Projects

- Support long-term maintenance and stewardship of parks and public access points through community engagement, policy change, and job creation.

- Assess and improve amenities at parks and public access points to improve accessibility and increase responsible public use.

- Explore creative maintenance approaches (*e.g.*, local community oversight) and green workforce development.

# Outputs

- New amenities and infrastructure to equitably serve visitors and protect the environment

- Long-term management plans and funding mechanisms

- New jobs dedicated to green and blue space management

- Community groups dedicated to maintaining access points in their communities

# Outcomes

- Safe, high-quality public access points and green spaces that are resilient and accessible to all

- Increased environmental workforce

- Increased visitor revenue and positive economic impact to areas with well-maintained green and blue space access

- Improved responsible enjoyment of nature by all communities

# Indicators

Precipitation, Sea Level, Population, Land Use, Water Quality Conditions for Recreation, Marine Beaches, Public Access, Open Space

# NBEP role

Fund capacity and projects, Synthesize and communicate science

# Implementing Partners

Groundwork RI, Groundwork Southcoast, Woonasquatucket River Watershed Council, Save The Bay, MA EOEEA, TNC-RI, Mass Audubon, ASRI, RI Land Trust Alliance, RI Saltwater Anglers Association

# Location

Narragansett Bay region, with a focus on areas with engaged partners or community groups

# Timeline for initiation

2026-2029

# Estimated costs/potential funding sources

\$5M–10M

States, municipalities, Private foundations
