---
title: "Action Public Spaces-1.2: Public Access Protection"
---

Action Statement: Develop policies and awareness campaigns to clarify and ensure legal access to shorelines and inland waterways.

# Action Description and Statement of Need

This Action will improve public access to shorelines and waterways by clarifying legal rights and policies for public rights-of-way and access points. Public awareness campaigns will help ensure those rights are understood and protected.

Connecticut, Rhode Island, and Massachusetts guarantee access to the coastal shore through the Public Trust Doctrine, which holds all submerged lands and water in the intertidal zone and waterward in trust for public use, including boating, fishing, swimming, etc. In Rhode Island, the public is guaranteed lateral shoreline access up to 10 feet landward of the noticeable high tide debris line, though there are pending legal actions against the 2023 Shoreline Access Law. In Connecticut, lateral access is up to the mean high tide line. In Massachusetts, the public can only use the shoreline below the low-tide mark and intertidal zone if involved in fishing, birding, hunting, and boating.

Public access to rivers, streams, and lakes is not universally protected. Most waterfront property is privately owned, so perpendicular access to the riverbank is more limited. As with coastal shorelines, without a legal right-of-way, public travel across private property to access the water is trespassing. Further, dams without portage create significant barriers to aquatic recreation.

Sometimes when a property transfers to a new owner, public access is blocked (Smith 2023). Property owners adjacent to rights-of-way and public access paths may discourage use by installing illegal no trespassing signs, no parking signs, physical barriers, or guards. In a 2023 Rhode Island CRMC survey, 41 percent of residents surveyed said they use local rights-of-way less often due to lack of parking, or feeling unsafe, unwelcome, or unsure about allowable use (Smith 2024). And increasingly, public access points are being lost to sea level rise and erosion in the wake of more intense storms.

Inequities exist in public access to the shoreline for mobility-impaired individuals without access to comparable amenities. Further, many urban residents must travel farther for legal access to high quality public coastal amenities (Twichell *et al.* 2022). In areas with limited access opportunities, loss or damage to access points due to storms and sea level rise further exacerbates inequities.

NBEP will fund capacity to clarify or develop policies and voice support for ensuring fair legal access to waterways, especially inland waterways where access issues have received less attention and scrutiny. NBEP will fund capacity to create informational campaigns to better educate residents and visitors alike on access and threats to access.

# Potential Projects

- Create and continue education and awareness campaigns to clarify public/private boundaries on the beach or along freshwater access points, prevent illegal signage, and ensure rights are protected.

- Develop policies that clarify legal rights to the shoreline and inland waterways and otherwise expand access in the region.

# Outputs

- Database of public access locations in the region and a new corresponding NBEP Public Access Indicator (NBEP 2023a)

- New information campaigns educating the public on their access rights

- New policies and initiatives to clarify state laws

# Outcomes

- Improved public understanding of how to access coastal and inland waters

- Improved public understanding of legal access rights to shorelines and waterways throughout the region

- Clarified state and municipal policies regarding access rights and rules for enforcement

# Indicators

Precipitation, Sea Level, Water Quality for Recreation, Marine Beaches, Public Access

# NBEP role

Fund capacity and projects, Synthesize and communicate science

# Implementing Partners

Save The Bay, URI Coastal Institute, Blackstone Watershed Collaborative, RWU, CRMC, RIDEM, RI Saltwater Anglers Association

# Location

Narragansett Bay region

# Timeline for initiation

Ongoing

# Estimated costs/potential funding sources

\$500K–1M

NBEP 320/SNEP, EPA SNEP, States
