---
title: "Action Public Spaces-2.1: Environmental Health Alerts"
---

::: {.callout-info}
# Full Action Statement

Develop and publicize education campaigns and public alert and incident reporting systems for environmental health risks.
:::

# Action Description and Statement of Need

This Action will help protect public health by developing and/or publicizing consistent and education campaigns and notification systems to alert resource users to unsafe environmental conditions. Partners will coordinate efforts to design and implement public outreach strategies to target and alert users at the right places, at the right times, and with accurate messaging.

Water quality improvements in the region’s estuaries and rivers have led to overall safer conditions for recreation and shellfish harvest [@nbep2017]. However, episodic harmful algal blooms, raw and partially treated sewage spills, and legacy contamination like mercury and PCBs still present threats to public health. In 2024, EPA issued updated recommendations for monitoring contaminants of emerging concern in locally caught freshwater fish. Raising public awareness of these environmental health risks is necessary to protect the health and enjoyment of those using the region’s recreational water resources.

Massachusetts and Connecticut, but not Rhode Island, have legal requirements for public notification when untreated sewage flows into State waters. In Rhode Island, the Narragansett Bay Commission operates an online Combined Sewer Overflow (CSO) Alarm Map, as required by their Pollutant Discharge Elimination System (RIPDES) permit. The City of Newport, which has one CSO discharge, does not operate an online overflow notification system. Rhode Island wastewater facilities are required to report sewer system overflows to both RIDEM and EPA, but not to the public. A comprehensive web-based public notification system, mandatory for all types of sewage discharges in Rhode Island, would contribute to public awareness and health protection.

State environmental agencies, some state and local health departments, and environmental organizations coordinate to monitor cyanobacteria blooms and toxins. In recent years, advisories have increased in number and duration [@ridem2023]. Rhode Island’s Department of Environmental Management and Department of Health issue waterbody-specific advisories, usually via signage, as capacity allows.

Legacy contamination of the region’s freshwaters makes most freshwater fish unsafe for human consumption [@kamman2005]. State Departments of Health provide recommendations for restricting fish consumption, especially for at-risk groups. Both Massachusetts and Rhode Island also issue advisories for specific waterbodies when warranted by available data. Public health agencies often work with medical providers and fishing license agencies to convey this information. However, given language barriers and lack of access to health providers among some user groups, additional effort is needed to expand outreach about unsafe finfish consumption.

The States have notification systems in the event shellfish are unsafe for harvest—RIDEM Office of Water Resources publicizes shellfish closures in near real-time through web postings, recorded message hotline, press releases, and email. Digital notification systems are more effective than signs or flags and could have even greater reach if distributed in multiple languages.

NBEP will help synthesize and communicate the science of environmental health risks associated with recreational use of local waters, coordinate partners to design shared multilingual education materials on environmental health risks, and fund capacity and projects to develop comprehensive public alert systems for environmental health risks.

# Potential Projects

-   Increase public awareness of CSO alert systems.

-   Create a public notification system for raw and partially treated sewage into Rhode Island waters.

-   Coordinate design of shared, consistent multilingual educational materials warning of priority environmental health risks.

-   Track WWTF and CSO permits for compliance and notification of violations.

# Outputs

-   Notification system for raw and partially treated sewage in Rhode Island waters

-   New multilingual alert materials for priority public health concerns

# Outcomes

-   Improved public health

-   Increased public awareness of water pollution and contamination problems and causes

# Indicators

Shellfishing Areas, Marine Beaches, Legacy Contaminants, Water Quality Conditions for Recreation, Water Quality Conditions for Aquatic Life

# NBEP role

Synthesize and communicate science, Fund capacity and projects

# Implementing Partners

MassDEP, RIDEM, EPA, RIDOH, Narragansett Bay Commission, Stormwater Innovation Center, URI Watershed Watch, NEIWPCC, RWU, Blackstone Watershed Collaborative, Blackstone River Coalition, Mass Audubon, Taunton River Watershed Alliance, Save The Bay, SRPEDD, MA EOEEA, Mass Rivers, RI Saltwater Anglers Association

# Location

Narragansett Bay region, with particular focus on freshwater resources for cyanobacteria and fish consumption alerts

# Timeline for initiation

2030-2032

# Estimated costs/potential funding sources

\$1M–5M

NBEP 320/SNEP, EPA/SNEP, State Funding, Sewage Notification Assistance Grant Program (MassDEP)
