---
title: "Appendix C. Crosswalk of 2012 and 2026 CCMPs"
---

+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| Action/Task                                                                                                                                                                                                                                                                                                                                               | Status of activity | 2026 CCMP Status | 2025 CCMP Action                                  |
+===========================================================================================================================================================================================================================================================================================================================================================+====================+==================+===================================================+
| 1.1.1 Issue and implement revised EPA New England permits for nutrient controls at wastewater treatment facilities (WWTFs) located in Mass. portion of the Blackstone River and Ten Mile River watersheds                                                                                                                                                 | Completed          | Obsolete         | N/A                                               |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 1.1.2 By 2014, complete upgrades needed to implement nutrient reductions at eleven R.I. WWTFs to achieve 50% reduction in total nitrogen discharges (May to October) from WWTFs discharging into upper Narragansett Bay or its major tributaries (2014)                                                                                                   | Completed          | Obsolete         | N/A                                               |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 1.1.3 Accelerate the elimination of cesspools by adoption of additional phase out requirements (2014)                                                                                                                                                                                                                                                     | Completed          | Obsolete         | N/A                                               |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 1.1.4 Reduce the impacts of residential and commercial septic systems on water quality by implementing inspection, maintenance and financial assistance programs, and promoting adoption of more effective treatment technologies                                                                                                                         | Ongoing            | Revised/Updated  | Water-3.2: Onsite Wastewater Systems\             |
|                                                                                                                                                                                                                                                                                                                                                           |                    |                  | People-3.1: Finance Plan                          |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 1.1.5 Pursue changes to state laws that will ensure that properties with onsite wastewater treatment systems in existing service areas will be connected to sewer lines                                                                                                                                                                                   | Obsolete           | Obsolete         | N/A                                               |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 1.1.6 Extend sewer service to critical areas with failing onsite waste systems including Island Park (Portsmouth) and areas surrounding Greenwich Bay.                                                                                                                                                                                                    | Ongoing            | Revised/Updated  | Water-3.1: Centralized Wastewater Infrastructure\ |
|                                                                                                                                                                                                                                                                                                                                                           |                    |                  | Water-3.2: Onsite Wastewater Systems              |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 1.1.7 Ensure that existing wastewater treatment and conveyance infrastructure is sufficiently maintained on an ongoing basis to detect, reduce instances of, and prevent Sanitary System Overflows (SSOs) and other system problems                                                                                                                       | Ongoing            | Revised/Updated  | Water-2.1: Stormwater Guidance and Education\     |
|                                                                                                                                                                                                                                                                                                                                                           |                    |                  | Water-2.2: Stormwater Retrofits and Maintenance\  |
|                                                                                                                                                                                                                                                                                                                                                           |                    |                  | Water-3.1: Centralized Wastewater Infrastructure  |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 1.1.8 Determine areas where advanced septic system treatment systems should be required to protect sensitive waters and other resources.                                                                                                                                                                                                                  | Ongoing            | Revised/Updated  | Water-3.2: Onsite Wastewater Systems              |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 1.2.1 Provide enhanced funding and technical assistance to municipalities in key areas of stormwater management – operations & maintenance, assessment, illicit detection, stormwater system retrofits, public communications, and financing                                                                                                              | Ongoing            | Revised/Updated  | Water-2.1: Stormwater Guidance and Education\     |
|                                                                                                                                                                                                                                                                                                                                                           |                    |                  | Water-2.2: Stormwater Retrofits and Maintenance   |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 1.2.2 Prioritize retrofitting of BMPs to areas most affected by stormwater impacts, using LID and including physical and habitat restoration where feasible to achieve water quality goals                                                                                                                                                                | Ongoing            | Revised/Updated  | Water-2.2: Stormwater Retrofits and Maintenance   |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 1.2.3 Evaluate compliance and effectiveness of existing Phase II MS4 permits; use this information to devise strategies and incentives to improve compliance                                                                                                                                                                                              | Ongoing            | Revised/Updated  | Water-2.2: Stormwater Retrofits and Maintenance\  |
|                                                                                                                                                                                                                                                                                                                                                           |                    |                  | Water-1.2: Land Use and Watershed Planning        |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 1.2.4 Use the Phase 2 stormwater permitting process as a tool to encourage more effective local management of stormwater including adequate maintenance, use of best management practices, and appropriate pre- and post-construction stormwater controls                                                                                                 | Ongoing            | Obsolete         | N/A                                               |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 1.2.5. Use the joint technical assistance RIDEM/MADEP project in the Blackstone, Ten Mile and other relevant stormwater efforts to pilot an approach for providing technical assistance to municipalities in implementing Phase II stormwater requirements                                                                                                | Obsolete           | Obsolete         | N/A                                               |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 1.2.6 Support regional efforts to reduce and manage fertilizer use                                                                                                                                                                                                                                                                                        | Ongoing            | Revised/Updated  | Public Spaces-1.2: Environmental Health Alerts    |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 1.2.7 Ensure that data systems capture information on stormwater BMPs to assess effectiveness and track performance                                                                                                                                                                                                                                       | Ongoing            | Revised/Updated  | Water-2.2: Stormwater Retrofits and Maintenance   |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 1.2.8 Update soil erosion and sediment control manuals in both Rhode Island and Massachusetts                                                                                                                                                                                                                                                             | Completed          | Obsolete         | Water-2.1: Stormwater Guidance and Education\     |
|                                                                                                                                                                                                                                                                                                                                                           |                    |                  | Water-1.2: Land Use and Watershed Planning        |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 1.2.9 State and local governments should work with retail operations to reduce or eliminate the use of single-use, non-biodegradable plastic bags through incentives, bans or other methods to reduce pollution of waterways and protect aquatic life                                                                                                     | Completed          | Obsolete         | N/A                                               |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 1.2.10 Enhance state DOTs capacity to construct prioritized stormwater retrofits using LID practices as identified in state stormwater manuals                                                                                                                                                                                                            | Obsolete           | Revised/Updated  | Water-2.1: Stormwater Guidance and Education      |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 1.3.1 Complete planned NBC Phase 2 by 2014 and initiate planning for Phase 3 that considers incorporating LID methods; complete CSO abatement projects in Newport (2015) and Fall River (2019)                                                                                                                                                            | Ongoing            | Revised/Updated  | Water-3.1: Centralized Wastewater Infrastructure  |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 1.3.2 Complete assessment of Providence CSO phase 1; report on results and assess effectiveness of other CSO projects as completed                                                                                                                                                                                                                        | Completed          | Obsolete         | N/A                                               |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 1.3.3 Identify and implement LID and urban green infrastructure programs and practices that will optimize the performance of CSO abatement projects                                                                                                                                                                                                       | Ongoing            | Revised/Updated  | Water-2.2: Stormwater Retrofits and Maintenance   |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 1.4.1 Implement scientifically-based water management to restore and protect streamflow and ensure sustainable yields including methodology that accounts for current and future land uses, impacts on aquatic systems and inter-basin transfers                                                                                                          | Ongoing            | Revised/Updated  | Habitat-2.1: Habitat Plans\                       |
|                                                                                                                                                                                                                                                                                                                                                           |                    |                  | Water-1.2: Land Use and Watershed Planning        |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 1.4.2 Fully utilize watershed-based plans, such as stakeholder-based plans, NPS plans, TMDLs, and special area management plans to coordinate prioritized actions to protect, restore and manage the land and water (including groundwater) resources within watersheds (2015)                                                                            | Ongoing            | Revised/Updated  | Habitat-2.1: Habitat Plans\                       |
|                                                                                                                                                                                                                                                                                                                                                           |                    |                  | Water-1.2: Land Use and Watershed Planning        |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 1.4.3 Build and increase capacity of nongovernmental organizations in implementing protection and restoration actions                                                                                                                                                                                                                                     | Ongoing            | Revised/Updated  | People-3.1: Finance Plan                          |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 1.4.4 Rhode Island and Massachusetts should work with EPA to identify nutrient management regimes that identify specific management goals or targets for nutrient levels in both states’ waterbodies                                                                                                                                                      | Ongoing            | Revised/Updated  | People-2.3: Indicators\                           |
|                                                                                                                                                                                                                                                                                                                                                           |                    |                  | People-3.2: Regional Targets                      |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 1.4.5 Update and implement state management plans to protect ground water and surface water resources from priority pollutant risks                                                                                                                                                                                                                       | Ongoing            | Revised/Updated  | Habitat-2.1: Habitat Plans\                       |
|                                                                                                                                                                                                                                                                                                                                                           |                    |                  | Water-1.2: Land Use and Watershed Planning        |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 1.5.1 Provide sufficient resources, staffing and operational funds to maintain and fill in gaps in existing monitoring and assessment programs in both Rhode Island and Massachusetts including designated monitoring coordinators in both states                                                                                                         | Ongoing            | Revised/Updated  | People-3.1: Finance Plan\                         |
|                                                                                                                                                                                                                                                                                                                                                           |                    |                  | Habitat-1.1: Habitat Monitoring\                  |
|                                                                                                                                                                                                                                                                                                                                                           |                    |                  | Water-1.1: Water Quality Monitoring               |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 1.5.2 Develop new or expand existing funding mechanisms at the state and local level (especially consider utility districts) to meet stormwater/water quality infrastructure needs                                                                                                                                                                        | Ongoing            | Revised/Updated  | People-3.1: Finance Plan                          |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 1.5.3 Advocate for adequate federal SRF and other federal funding for water and wastewater infrastructure, stormwater treatment, and nonpoint source pollution management and other actions in an approved CCMPs and nonpoint source management plans                                                                                                     | Ongoing            | Revised/Updated  | People-3.1: Finance Plan\                         |
|                                                                                                                                                                                                                                                                                                                                                           |                    |                  | Water-2.2: Stormwater Retrofits and Maintenance\  |
|                                                                                                                                                                                                                                                                                                                                                           |                    |                  | Water-3.1: Centralized Wastewater Infrastructure  |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 1.5.4 Support and advocate for environmental bond funds in both states to support water quality and resource goals                                                                                                                                                                                                                                        | Ongoing            | Revised/Updated  | People-3.1: Finance Plan                          |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 1.5.5 Develop mechanism (*e.g.*, regional workgroup) to examine local capacity to implement required environmental programs; examine regional solutions; report on funding issues related to local capacity to implement                                                                                                                                  | Ongoing            | Revised/Updated  | People-1.1: Engagement Plan\                      |
|                                                                                                                                                                                                                                                                                                                                                           |                    |                  | People-3.1: Finance Plan                          |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 1.5.6 Develop improved state mechanisms that efficiently distribute and manage small grants to partner organizations and facilitate access to grant funding while meeting governmental fiscal management requirements; examine governmental fiscal management requirements for improvements that will advance this action                                 | Completed          | Obsolete         | N/A                                               |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 1.5.7 Continue support for the R.I. CSSLP program to encourage cesspool removal and OWTS upgrade; in Massachusetts, consider adopting a funding mechanism similar to the R.I. Community Septic System Loan Program (CSSLP)                                                                                                                                | Completed          | Obsolete         | N/A                                               |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 1.5.8 In non-sewered areas, increase the number of municipalities that participate in R.I.’s CSSLP                                                                                                                                                                                                                                                        | Ongoing            | Obsolete         | Water-3.2: Onsite Wastewater Systems              |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 1.6.1 Effectively manage, analyze, synthesize and make available data to support management decision-making, characterize environmental condition trends linked to ecological indicators, prioritize investments and communicate to the public. Continue development of data driven analytical tools, *e.g.*, predictive models, biological indices, etc. | Ongoing            | Revised/Updated  | People-2.1: Science Communication Tools\          |
|                                                                                                                                                                                                                                                                                                                                                           |                    |                  | People-2.2: Ecosystem Modeling                    |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 1.6.2 Ensure public access to water quality and other monitoring data acquired with public funds; where not required, require that permit and grant-funded monitoring data be submitted in an accessible digital format (2014)                                                                                                                            | Ongoing            | Revised/Updated  | People-2.1: Science Communication Tools\          |
|                                                                                                                                                                                                                                                                                                                                                           |                    |                  | People-2.2: Ecosystem Modeling                    |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 1.6.3 Support and develop volunteer monitoring programs where appropriate, building on existing volunteer monitoring programs; where feasible ensure resulting data helps fill gaps and has adequate quality assurance / quality control parameters to be used for state purposes                                                                         | Ongoing            | Revised/Updated  | People-1.1: Engagement Plan\                      |
|                                                                                                                                                                                                                                                                                                                                                           |                    |                  | Habitat-1.12: Habitat Monitoring\                 |
|                                                                                                                                                                                                                                                                                                                                                           |                    |                  | Water-1.1: Water Quality Monitoring               |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 1.6.4 Work with universities and federal agencies to improve scientific knowledge of water resource issues and technology including climate change implications and emerging contaminants; integrate new findings into management schemes                                                                                                                 | Ongoing            | Revised/Updated  | People-1.2: Research Plan\                        |
|                                                                                                                                                                                                                                                                                                                                                           |                    |                  | People-2.1: Science Communication Tools\          |
|                                                                                                                                                                                                                                                                                                                                                           |                    |                  | People-2.2: Ecosystem Modeling\                   |
|                                                                                                                                                                                                                                                                                                                                                           |                    |                  | People-2.3: Indicators\                           |
|                                                                                                                                                                                                                                                                                                                                                           |                    |                  | Habitat-1.1: Habitat Monitoring\                  |
|                                                                                                                                                                                                                                                                                                                                                           |                    |                  | Water-1.1: Water Quality Monitoring               |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 1.6.5 Measure progress and provide the public with ongoing reports on key water quality implementation progress, *e.g.*, TMDLs, nutrients, stormwater                                                                                                                                                                                                     | Ongoing            | Revised/Updated  | People-2.3: Indicators\                           |
|                                                                                                                                                                                                                                                                                                                                                           |                    |                  | People-3.2: Regional Targets\                     |
|                                                                                                                                                                                                                                                                                                                                                           |                    |                  | People-2.1: Science Communication Tools\          |
|                                                                                                                                                                                                                                                                                                                                                           |                    |                  | People-2.2: Ecosystem Modeling                    |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 2.1.1 Develop and adopt state and local policies, regulations, and ordinances as needed to fully implement low impact development approaches to development and redevelopment                                                                                                                                                                             | Ongoing            | Revised/Updated  | Water-1.2: Land Use and Watershed Planning        |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 2.1.2 Provide technical assistance to municipalities to identify and implement green infrastructure and LID techniques; agencies should assign designated staff as point of contact on LID issues (permits, training, technical assistance, etc.)                                                                                                         | Ongoing            | Revised/Updated  | Water-2.1 Stormwater Guidance and Education       |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 2.1.3 Develop and implement incentive programs to provide LID-based treatment to existing impervious surface areas not covered by current regulatory requirements                                                                                                                                                                                         | Ongoing            | Obsolete         | N/A                                               |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 2.2.1 Identify and prioritize areas for acquisition, protection and restoration on an interstate basis; target acquisition of priority areas                                                                                                                                                                                                              | Ongoing            | Revised/Updated  | Water-1.2: Land Use and Watershed Planning        |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 2.2.2 Prioritize and permanently protect open space areas in both states that are now under non-permanent protection status (time-limited development rights, etc.)                                                                                                                                                                                       | Ongoing            | Revised/Updated  | Water-1.2: Land Use and Watershed Planning\       |
|                                                                                                                                                                                                                                                                                                                                                           |                    |                  | Public Spaces-1.1: New Public Access\             |
|                                                                                                                                                                                                                                                                                                                                                           |                    |                  | Public Spaces-1.2: Public Access Protection       |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 2.2.3 Provide technical assistance, grants and financial and permitting incentives to expand use of conservation development designs and ordinances                                                                                                                                                                                                       | Ongoing            | Revised/Updated  | Water-1.2: Land Use and Watershed Planning        |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 2.3.1 Direct sustainable growth through targeting grant funds, state investments and incentives for redevelopment, infrastructure improvements and/or added capacity to developed lands including Brownfield sites (in R.I., to state-designated urban service boundary and growth centers)                                                               | Ongoing            | Revised/Updated  | Water-1.2: Land Use and Watershed Planning        |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 2.3.2 Work with municipalities to promote growth within the urban service boundaries by implementing RI Land Use 2025 and similar measures in Massachusetts; for communities outside of urban service boundaries, develop criteria and incentives to properly locate new growth centers                                                                   | Ongoing            | Revised/Updated  | Water-1.2: Land Use and Watershed Planning        |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 2.3.3 Enhance existing or develop new mechanisms to provide planning resources to communities                                                                                                                                                                                                                                                             | Ongoing            | Revised/Updated  | People-3.2: Finance Plan                          |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 2.3.4 Revamp transportation systems to enable greater intermodal connections and promote alternatives to reliance on individual vehicles                                                                                                                                                                                                                  | Obsolete           | Obsolete         | N/A                                               |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 2.4.1 Increase public access to watershed resources by developing public water and land trail systems that enable a range of user opportunities (2014)                                                                                                                                                                                                    | Ongoing            | Revised/Updated  | Public Spaces-1.1: New Public Access              |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 2.4.2 Require public access where feasible in development and redevelopment projects that abut public waterbodies and river shorelines in both states (2015)                                                                                                                                                                                              | Ongoing            | Revised/Updated  | Public Spaces-1.1: New Public Access\             |
|                                                                                                                                                                                                                                                                                                                                                           |                    |                  | Public Spaces-1.3: Public Access Management       |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 2.4.3 Continue to plan and develop public fishing piers, boat ramps and other forms of public access to fresh and salt waters in the Narragansett Bay Region                                                                                                                                                                                              | Ongoing            | Revised/Updated  | Public Spaces-1.1: New Public Access              |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 2.4.4 Improve, expand and promote coastal rights-of-way designations (assessment, signage, mapping, parking) in both states                                                                                                                                                                                                                               | Ongoing            | Revised/Updated  | Public Spaces-1.2: Public Access Protection       |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 2.4.5 Identify and address obstacles that impede public access to freshwater sites in both states                                                                                                                                                                                                                                                         | Ongoing            | Revised/Updated  | Public Spaces-1.2: Public Access Protection       |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 2.5.1 Use communications and outreach efforts to promote important watershed resources and ways in which citizens and governments can protect and restore the value of these resources                                                                                                                                                                    | Ongoing            | Revised/Updated  | People-1.1: Engagement Plan                       |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 2.5.2 Create a mechanism to assess cumulative impacts of development at regional and bi-state watershed scales                                                                                                                                                                                                                                            | Obsolete           | Obsolete         | N/A                                               |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 2.6.1 R.I. and Massachusetts should provide technical planning resources to towns in less developed areas to proactively protect ecological resources and to support implementation of state and federal environmental regulatory requirements (2015)                                                                                                     | Ongoing            | Revised/Updated  | People-3.2: Finance Plan                          |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 2.6.2 Provide technical assistance to local NGOs and watershed groups to support local implementation of environmental improvement projects; include structuring state and federal funding opportunities in ways that facilitate participation by those groups                                                                                            | Ongoing            | Revised/Updated  | People-3.2: Finance Plan                          |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 2.6.3 Pass legislation in Massachusetts that addresses the reforms included in the Comprehensive Land Use Reform & Partnership Act                                                                                                                                                                                                                        | Ongoing            | Obsolete         | N/A                                               |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 2.6.4 Massachusetts and Rhode Island communities should update community master plans to meet current state requirements                                                                                                                                                                                                                                  | Obsolete           | Obsolete         | N/A                                               |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 2.6.5 Massachusetts should broaden municipal participation in adopting the Community Preservation Act                                                                                                                                                                                                                                                     | Ongoing            | Revised/Updated  | Water-1.2: Land Use and Watershed Planning        |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 2.6.6 Support bi-state cooperative work by nongovernmental organizations like the Blackstone River Coalition and the Taunton River Watershed Alliance                                                                                                                                                                                                     | Ongoing            | Revised/Updated  | People-3.2: Finance Plan                          |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 2.6.7 Develop training and information programs for conservation commissions to help communities meet planning and regulatory needs; transfer lessons learned from Mass. conservation commissions                                                                                                                                                         | Ongoing            | Revised/Updated  | Water-1.2: Land Use and Watershed Planning        |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 3.1.1 Focus resources and enhance land protection efforts by conservation agencies and organizations on less-developed areas, particularly areas threatened by new sprawl development in both states                                                                                                                                                      | Obsolete           | Obsolete         | N/A                                               |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 3.1.2 Improve and coordinate both state and federal habitat protection and restoration policies                                                                                                                                                                                                                                                           | Ongoing            | Revised/Updated  | Habitat-2.1: Habitat Plans                        |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 3.2.1 Improve river connectivity and habitat by removing dams, upgrading culverts and creating structural fish ways to restore free-flowing rivers and anadromous fish passage; implement state fish passage plans                                                                                                                                        | Ongoing            | Revised/Updated  | Habitat-2.1: Aquatic Connectivity                 |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 3.2.2 Create a coordinated bi-state habitat sustainability strategy with a restoration component and identification of priority projects, comprehensive management principles, and implementation targets for freshwater and saltwater ecosystems (2015)                                                                                                  | Obsolete           | Obsolete         | N/A                                               |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 3.2.3 Develop a strategy to assess dams comprehensively addressing public safety, ecology, cultural values, and power generation                                                                                                                                                                                                                          | Ongoing            | Revised/Updated  | Habitat-3.1: Aquatic Connectivity                 |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 3.3.1 Manage waterfowl populations to reduce bacterial and nutrient pollution and habitat destruction in waterbodies                                                                                                                                                                                                                                      | Ongoing            | Obsolete         | N/A                                               |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 3.3.2 Create and implement a comprehensive shellfish management plan for all R.I. marine waters including Massachusetts marine waters in Narragansett Bay that recognizes shellfish as an ecological as well as an economic resource (2014)                                                                                                               | Completed          | Revised/Updated  | Habitat-2.1: Habitat Plans                        |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 3.3.3 Assess and consider for use in Rhode Island the Massachusetts Conservation Assessment and Prioritization System (CAPS) to evaluate the integrity of ecological communities                                                                                                                                                                          | Ongoing            | Ongoing          | Habitat-2.1: Habitat Plans                        |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 3.3.4 Acquire needed data to revise and implement R.I. and Mass. wildlife plans that address important species and associated habitats identified by the states and The Nature Conservancy                                                                                                                                                                | Ongoing            | Revised/Updated  | Habitat-2.1: Habitat Plans                        |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 3.3.5 Develop and sustain wildlife monitoring programs                                                                                                                                                                                                                                                                                                    | Ongoing            | Revised/Updated  | Habitat-1.1: Habitat Monitoring                   |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 3.3.6 Educate landowners, resource users and the public regarding habitat and wildlife conservation                                                                                                                                                                                                                                                       | Ongoing            | Revised/Updated  | People-1.1: Engagement Plan                       |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 3.3.7 Identify and protect cold water fishery streams/headwater areas using Clean Water Act tools, state, federal, and non-profit land acquisition programs and other strategies                                                                                                                                                                          | Ongoing            | Revised/Updated  | Habitat-2.1: Habitat Plans                        |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 3.4.1 Update and implement state plans for preventing, controlling and managing terrestrial and aquatic invasive species including improving early detection and rapid response capabilities and educating key constituencies; coordinate R.I. and Mass. programs                                                                                         | Ongoing            | Revised/Updated  | Habitat-2.1: Habitat Plans                        |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 3.5.1 Establish a comprehensive set of NBR status and trends indicators for critical habitats to assess habitat changes (working off biological condition gradient), impacts, and conservation and restoration progress (2014)                                                                                                                            | Completed          | Revised/Updated  | People-2.3: Indicators                            |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 3.5.2 Restore/re-fund Rhode Island Natural Heritage program through a multi-organization partnership                                                                                                                                                                                                                                                      | Ongoing            | Revised/Updated  | People-3.1: Finance Plan\                         |
|                                                                                                                                                                                                                                                                                                                                                           |                    |                  | Habitat-2.1: Habitat Plans                        |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 3.5.3 Continue and enhance ecological approaches to fisheries management including monitoring, applied research, technical training                                                                                                                                                                                                                       | Ongoing            | Obsolete         | N/A                                               |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 3.5.4 Improve fish contamination studies and consumption advisories, particularly as pertains to urban and ethnic communities and populations at risk.                                                                                                                                                                                                    | Ongoing            | Revised/Updated  | Public Spaces- 2.1: Environmental Health Alerts   |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 3.5.5 Examine science and assess need for additional land and water protections, including identifying applied research needs related to habitat and habitat function; provide resources to conduct needed research.                                                                                                                                      | Ongoing            | Revised/Updated  | People-2.1: Research Plan\                        |
|                                                                                                                                                                                                                                                                                                                                                           |                    |                  | Habitat-2.1: Habitat Plans                        |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 3.5.6 Identify compatibility issues related to hydroelectric power generation and river ecosystems; incorporate into hydropower development strategies                                                                                                                                                                                                    | Obsolete           | Obsolete         | N/A                                               |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 3.5.7 Develop tools and information on biodiversity and priority habitats and make them available to the public and local and other officials to help with planning and management                                                                                                                                                                        | Ongoing            | Revised/Updated  | People-1.1: Engagement Plan                       |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 3.5.8 Develop incentives for private property owners to participate in habitat restoration projects                                                                                                                                                                                                                                                       | Ongoing            | Revised/Updated  | People-1.1: Engagement Plan                       |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 3.5.9 Working with commercial fishermen and shellfishermen, NBNERR, universities, angler associations and other community and technical stakeholders, examine potential for additional protected areas in Narragansett Bay and other coastal waters.                                                                                                      | Ongoing            | Revised/Updated  | People-1.1: Engagement Plan\                      |
|                                                                                                                                                                                                                                                                                                                                                           |                    |                  | Habitat-2.1 Habitat Plans                         |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 3.5.10 Use hydrographic models of the Bay and other methods to assess the relationship between areas closed to shellfishing due to pollution and shellfish harvest areas in terms of effects on shellfish populations and potential use of sanctuary or refuge areas for shellfish                                                                        | Ongoing            | Revised/Updated  | People-2.2: Ecosystem Modeling                    |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 3.5.11 Develop baseline data on condition and extent of riparian buffer areas                                                                                                                                                                                                                                                                             | Obsolete           | Obsolete         | N/A                                               |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 3.6.1 Create a R.I. Habitat Restoration program, similar to the Mass. Wetlands Restoration Division of Ecological Restoration, with dedicated, full-time staff to support project implementation, work on needed restoration policy, and integrate agency actions                                                                                         | Ongoing            | Ongoing          | People-3.2: Finance Plan                          |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 3.6.2 Develop state policies, plans and practices to improve integration of water quality improvement, stormwater measures and physical restoration                                                                                                                                                                                                       | Ongoing            | Revised/Updated  | Water-2.1: Stormwater Guidance and Education\     |
|                                                                                                                                                                                                                                                                                                                                                           |                    |                  | Habitat-2.1: Habitat Plans\                       |
|                                                                                                                                                                                                                                                                                                                                                           |                    |                  | Habitat-2.2: Habitat Projects                     |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 3.6.3 Support and expand R.I. Coastal and Estuarine Habitat Restoration Trust Fund funding, the Mass. Division of Ecological Restoration, NGO-based restoration efforts and federally funded restoration programs (NRCS, USFWS, NBEP, etc.) (2015)                                                                                                        | Ongoing            | Revised/Updated  | People-3.2: Finance Plan                          |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 3.6.4 Maintain and expand state-wide and regional mapping of critical watershed and coastal habitats including biodiversity hot spots; use data to support restoration, conservation planning, and enhanced enforcement                                                                                                                                   | Ongoing            | Revised/Updated  | People-2.2: Ecosystem Modeling                    |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 3.6.5 Support the efforts of the R.I. Habitat Restoration Team to improve and coordinate habitat restoration projects, funding and policy                                                                                                                                                                                                                 | Ongoing            | Revised/Updated  | People-3.2: Finance Plan                          |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 3.6.6 Develop a continuing seagrass mapping program in R.I. and Mass. coastal waters                                                                                                                                                                                                                                                                      | Ongoing            | Revised/Updated  | People-1.2: Research plan                         |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 3.6.7 Create R.I. state lake management program, coordinated with Mass. lakes management that includes requirements for lake management plans that address water quality and invasive species.                                                                                                                                                            | Completed          | Obsolete         | Habitat-2.1: Habitat Plans                        |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 4.1.1 Identify, protect and restore watershed and riverine natural resources, *e.g.*, wetlands and riparian areas to ensure their continuance as cost-effective protection                                                                                                                                                                                | Ongoing            | Revised/Updated  | Habitat-2.1: Habitat Plans                        |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 4.1.2 Remove dams where practicable and beneficial to public safety and/or river ecology; where dams must be retained, ensure that high and moderate hazard dams are fully maintained                                                                                                                                                                     | Ongoing            | Revised/Updated  | Habitat-3.1: Aquatic Connectivity                 |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 4.1.3 Improve dam condemnation policies to provide more effective mechanisms for dam removal in R.I. and Mass.                                                                                                                                                                                                                                            | Ongoing            | Revised/Updated  | Habitat-3.1: Aquatic Connectivity                 |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 4.1.4 Use state and local permitting processes and adaptive restoration programs (*e.g.*, living shorelines) to protect natural coastal features like salt marshes and beaches as well as coastal shoreline processes so that they can continue to provide cost-effective coastal protection.                                                             | Ongoing            | Ongoing          | Habitat-3.2: Salt Marsh Restoration               |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 4.2.1 Develop strategies and incentives to guide development away from high hazard zones and natural areas that provide storm protection and other benefits (2015)                                                                                                                                                                                        | Ongoing            | Revised/Updated  | Habitat-3.2: Salt Marsh Restoration               |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 4.2.2 Design stormwater treatment facilities and green stormwater infrastructure to have adequate capacity over the life of the facility for predicted increased, intensified flow resulting from climate change (2017)                                                                                                                                   | Completed          | Revised/Updated  | Water-1.2: Stormwater Retrofits                   |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 4.2.3 Develop and implement natural hazard mitigation and adaptation plans for publicly-owned wastewater facilities to reduce potential for pollution impacts from climate related events                                                                                                                                                                 | Completed          | Revised/Updated  | Water-2.1: Centralized Wastewater Infrastructure  |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 4.2.4 Improve dam inspection and maintenance requirements and enforcement                                                                                                                                                                                                                                                                                 | Ongoing            | Obsolete         | N/A                                               |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 4.2.5 Mandate a regular review of state and local plans and risk assessments to incorporate advancements in coastal hazards science                                                                                                                                                                                                                       | Ongoing            | Revised/Updated  | Habitat-2.1: Habitat Plans                        |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 4.2.6 Evaluate the projected effects of saltwater intrusion on coastal onsite wastewater treatment systems, drinking water and stormwater infrastructure                                                                                                                                                                                                  | Ongoing            | Obsolete         | N/A                                               |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 4.3.1 Develop a shoreline change Special Area Management Plan to address coastal erosion and inundation in response to sea level rise and strategies and incentives to guide development away from special flood hazard areas (2015)                                                                                                                      | Completed          | Revised/Updated  | People-3.2: Regional Targets                      |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 4.3.2 Develop mechanisms to coordinate responses across the range of interests affected by climate change impacts – state and federal agencies, private sector, institutions, and municipalities                                                                                                                                                          | Obsolete           | Obsolete         | N/A                                               |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 4.3.3 Create coordinated water release and storage strategies to help address problems related to flows (flooding, infrastructure damage, etc.) from intense storm events.                                                                                                                                                                                | Ongoing            | Revised/Updated  | Water-3.1: Centralized Wastewater Infrastructure  |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 4.3.4 Assess and identify the most effective adaptation responses; prioritize implementation of these identified activities (2015)                                                                                                                                                                                                                        | Ongoing            | Revised/Updated  | Water-2.1: Stormwater Guidance and Education\     |
|                                                                                                                                                                                                                                                                                                                                                           |                    |                  | Water-2.2: Stormwater Retrofits and Maintenance\  |
|                                                                                                                                                                                                                                                                                                                                                           |                    |                  | Water-1.2: Land Use and Watershed Planning        |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 4.4.1 Develop funding mechanisms for infrastructure retrofits for affected utilities and structures most likely to be affected by a disaster; identify those critical to public health and environmental priorities (2015)                                                                                                                                | Completed          | Revised/Updated  | People-3.1: Finance Plan                          |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 4.4.2 Develop additional funding for prioritized dam inspection, maintenance and removal; identify potential funding mechanisms to create a dam management fund                                                                                                                                                                                           | Ongoing            | Revised/Updated  | People-3.1: Finance Plan                          |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 4.4.3 Develop/leverage funding for acquisition of properties most vulnerable to damage from climate change impacts, targeting those which could provide multiple benefits such as habitat retreat, recharge, open space, recreation, and flood storage                                                                                                    | Ongoing            | Revised/Updated  | Habitat-2.2: Habitat Plans                        |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 4.4.4 Modify and enhance state State Revolving Fund programs to encourage communities to address climate change impacts and avoid investment in highly vulnerable areas                                                                                                                                                                                   | Ongoing            | Revised/Updated  | Water-3.2: Onsite Wastewater Systems              |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 4.4.5 Increase state resources and secure additional federal resources to meet identified science research needs                                                                                                                                                                                                                                          | Ongoing            | Ongoing          | People-2.1: Research Plan                         |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 4.5.1 Continue to improve accuracy of inundation models for coastal and riverine floodplains to support long term planning; apply the results of state pilot projects and NEP Climate Ready Estuaries projects in planning for resilience                                                                                                                 | Ongoing            | Revised/Updated  | People-2.2: Ecosystem Modeling\                   |
|                                                                                                                                                                                                                                                                                                                                                           |                    |                  | Habitat-2.1: Habitat Plans                        |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 4.5.2 Identify applied research needs to better assess impacts of climate change on watershed and bay ecosystems                                                                                                                                                                                                                                          | Ongoing            | Revised/Updated  | People-1.2: Research Plan                         |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 4.5.3 Use data generated by regional Light Detection and Ranging (LIDAR) topographic surveys and high-resolution bathymetry databases to support floodplain mapping, sea-level rise and storm surge modeling                                                                                                                                              | Ongoing            | Revised/Updated  | People-2.2: Ecosystem Modeling                    |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 4.6.1 Develop land conservation and adaptation plans for wetland migration to include protection of adjacent upland areas (2015)                                                                                                                                                                                                                          | Ongoing            | Revised/Updated  | Habitat-3.2: Salt Marsh Restoration               |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 4.6.2 Assess effectiveness and determine feasibility for use of Living Shorelines programs in the Narragansett Bay Region                                                                                                                                                                                                                                 | Obsolete           | Obsolete         | N/A                                               |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
| 4.6.3 Adopt an approach, where possible, that accommodates rather than resists flood waters by restoring floodplain buffers for use as marsh or forest land; Employ resilience design where possible to absorb stormwater in extreme events, particularly in light of projected increased precipitation                                                   | Obsolete           | Obsolete         | N/A                                               |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+------------------+---------------------------------------------------+
