---
title: "Action Water-2.2: Stormwater Retrofits and Maintenance"
---

::: {.callout-info}
# Full Action Statement

Support stormwater retrofit opportunities and associated maintenance activities to improve resilience and treatment capacity.
:::

# Action Description and Statement of Need

This Action will support design, construction, and maintenance of stormwater retrofit projects, especially green infrastructure BMPs, that improve water quality, help mitigate flooding, and increase resilience to intensifying precipitation.

Green infrastructure BMP retrofits, which use filtration, infiltration, and evapotranspiration to treat and soak up rainwater where it falls, can deliver environmental, social, and economic benefits beyond stormwater management alone. Retrofits can augment underperforming or failing systems or add additional capacity or lifespan to functioning systems. Examples of common green infrastructure BMPs in urban and suburban environments include bioswales, cisterns and rain barrels, dry wells and infiltration trenches, rain gardens and bioretention, permeable paving, and trees. New technologies and approaches continue to evolve [@snep2022]. For example, by using green infrastructure BMP retrofits alongside other water quality improvement actions, the bacterial impairment for recreation use in Greenwich Cove was removed from Rhode Island’s 2016 303(d) list of impaired waters. The project featured stormwater catch basin upgrades, street sweeping, sewer main replacement, correcting illicit connections, and connecting a failing septic system to central sewer. Greenwich Cove remains on the Rhode Island 303(d) list for other impairments.

Farms can also implement stormwater BMPs such as manure management, manure retaining systems, conservation buffers, and livestock fencing. In the Narragansett Bay watershed, state Natural Resources Conservation Service (NRCS) offices and conservation districts assist farmers and ranchers with creating conservation plans and implementing beneficial practices.

Ongoing maintenance and monitoring of stormwater infrastructure are essential to ensure optimal performance throughout its lifespan. Neglecting maintenance can lead to infrastructure failure, posing safety risks, degrading water quality, and ultimately requiring more time and resources to repair than regular maintenance would have required. To protect these investments, the region must prioritize sustained maintenance and monitoring. This approach will help extend infrastructure lifespan, reveal its full treatment and retention capacities, clarify the level of effort required for upkeep, and support the development of accurate replacement timelines.

Further, there is a need to develop sustainable financing mechanisms for stormwater project construction, maintenance, and monitoring, especially for overburdened, under-resourced, and under-staffed communities.

NBEP will fund studies and planning efforts that lead to stormwater retrofits, with a focus on green infrastructure opportunities. NBEP will also support projects that lead to greater understanding of stormwater infrastructure maintenance needs. Finally, NBEP will support efforts to develop sustainable financing mechanisms for stormwater management.

# Potential Projects

-   Support under-resourced and under-staffed communities to design and implement holistic and coordinated landscape-scale approaches to meeting stormwater requirements.

-   Fund studies and efforts to develop sustainable financing mechanisms to support more effective stormwater management at state and local levels.

-   Support partners to work with farms to develop and implement Conservation Plans that identify BMPs that mitigate stormwater impacts.

# Outputs

-   Retrofit designs

-   Completed retrofit projects

-   Stormwater retrofit funding mechanisms

# Outcomes

-   Water quantity and quality are better managed

-   Public health and property are better protected from the impacts of stormwater

-   Municipalities have reliable funding pathways for stormwater retrofits and maintenance

-   Expanded use of green infrastructure

# Indicators

Precipitation, Impervious Cover, Wastewater Infrastructure, Water Quality Condition for Aquatic Life, Water Quality Condition for Recreation, Marine Beaches, Shellfishing Areas

# NBEP role

Fund capacity and projects

# Implementing Partners

EPA, RIDOT, MassDOT, RIDEM, MassDEP, Narragansett Bay Commission, Stormwater Innovation Center, municipalities, Mass Audubon, Woonasquatucket River Watershed Council, Blackstone Watershed Collaborative, MA EOEEA, Save The Bay, SNEP Network, Conservation Districts

# Location

Tasks will be targeted to specific areas identified by analyses or prioritized by partners as pollution or flooding hotspots to maximize co-benefits.

# Timeline for initiation

2030-2032

# Estimated costs/Potential funding sources

\$10M+

NBEP 320/SNEP, NBEP BIL, SNEP, EPA, MRP, MVP, MassDEP CWA Section 604(b) Water Quality Management Planning Grant, MassDEP CWA Section 319 Nonpoint Source Implementation Grant, RIDEM CWA Section 319 Nonpoint Source Implementation Grant, NRCS EQIP
