---
title: "Action Water-1.1: Water Quality Monitoring"
---

::: {.callout-info}
# Full Action Statement

Support, improve, and create efficiencies for water quality monitoring programs to continue to provide information needed for management decision-making and filling knowledge gaps.
:::

# Action Description and Statement of Need

This Action will advance collection and use of water quality monitoring data to enhance management decision-making, track progress towards environmental and human health protection and restoration targets, and fill priority knowledge gaps.

Water quality monitoring is required for states to ensure compliance with federal and state regulations, inform management decisions to protect environmental and human health, and track changes to the ecosystem through time. Water quality monitoring includes water column chemistry (*e.g.,* nutrient concentrations, dissolved oxygen concentration, temperature, salinity, pH) and biological responses to pollution (*e.g.,* chlorophyll-*a* concentrations, bacteria concentrations, or macroinvertebrate abundances).

Monitoring data have been collected by multiple groups since the 1950s, including federal, state, and municipal agencies, non-profits, NGOs, universities, and communities. Many groups receive state funding to provide their data, which are used to build and calibrate models, create decision-support tools, and support restoration and environmental targets. Regionally, these groups work collaboratively to identify gaps in data collection, discuss emergent monitoring technologies, and ensure their data are consistent and useful.

Robust monitoring programs are essential to supporting the Clean Water Act and provide important information for assessing and anticipating the changing vulnerabilities of ecosystems and coastal communities. Development, land use changes, and restoration activities can alter water quality. Monitoring efforts need additional staff capacity and funding to expand to areas that require more attention without compromising data collection in other locations.

NBEP will support statewide monitoring strategy development and collaborate with partners across state boundaries to discuss monitoring activities. Participating on the Rhode Island Environmental Monitoring Collaborative, or other regional initiatives focused on monitoring should be a key activity. Additionally, NBEP may convene topic specific working groups to update methodologies, plan monitoring expansion into new locations, and revise protocols to prioritize efficiency and incorporate new partners.

NBEP will work with partners to develop and update monitoring databases and connect users with data. This could include identifying capacity, funding, and support for existing initiatives, such as the Narragansett Bay Data Portal or Snapshot of the Bay.

# Potential Projects

-   Facilitate Science Advisory Committee and staff participation on the RI Environmental Monitoring Collaborative to provide multi-state support for cross-boundary monitoring needs including coordinating or standardizing monitoring activities and methods, developing new or expanding current monitoring activities (such as water column chemistry, emerging pollutants, or increased focus on embayments), and ensure that monitoring aligns with management questions and needs.

-   Develop and/or update water quality monitoring databases.

-   Support expanded water quality monitoring in newly restored areas, such as the Kickemuit River, to establish a scientific basis for considering recreation and shellfish harvesting.

-   Facilitate Science Advisory Committee participation in the update to the Rhode Island Statewide Water Monitoring Strategy (2026).

-   Support innovations in monitoring strategies that bring efficiencies to and build capacity for data collection; encourage community science programs that help fill priority data gaps.

-   Support innovations for funding and staff capacity to continue data collection, analysis, and reporting.

# Outputs

-   New monitoring protocols or programs for new or expanded monitoring activities

-   Appropriately updated water quality databases and Statewide Water Monitoring Strategies

# Outcomes

-   Enhanced capacity for water quality monitoring throughout the region

-   Better coordinated water monitoring activities

-   Improved collection and use of water quality information

-   Enhanced understanding of monitoring gaps and mechanisms to fill them

-   Ecosystem management that is better informed by monitoring

# Indicators

All indicators

# NBEP role

Convene, Fund capacity and projects

# Implementing Partners

RIDEM, MassDEP, URI Coastal Institute, RI Environmental Monitoring Collaborative, NBNERR, TNC (RI and MA), Salt Ponds Coalition, URI Watershed Watch, Save The Bay, Brown University, URI, Narragansett Bay Commission, EPA-ORD-ACESD

# Location

Narragansett Bay region

# Timeline for initiation

2026-2029

# Estimated costs/potential funding sources

\$5M–10M

NBEP 320/SNEP, National Science Foundation, Congressionally Directed Spending, Foundation Grants, URI-CI, RIDEM, MassDEP, TNC
