---
title: "Action Water-1.2: Land Use and Watershed Planning"
---

::: callout-info
## Full Action Statement

Work at multiple scales to assess land use changes and develop plans and tools to protect watersheds.
:::

## Action Description and Statement of Need

Rhode Island, Massachusetts, and Connecticut are three of the top five most densely-populated states in the nation. The proportion of developed land in the Narragansett Bay region is increasing at a rapid pace due to trends in development practices including larger lots with single-family homes and increases in single-use areas that separate industrial, business, and civic uses [@nbep2021c]. Impacts from urban sprawl and its associated land use changes include increased pollutants from point and nonpoint sources, alteration of hydrologic processes, such as infiltration, runoff, and stream flows, and impacts to associated habitats, such as wetlands and stream environments. Proactive land use and watershed planning can mitigate negative impacts by managing the use of land and water resources in a comprehensive manner by working at different planning scales.

Each state in the Narragansett Bay region maintains statewide planning documents that outline goals for land use within their borders. These forward-looking plans analyze projected population change, growth of developed land, and assess how to best balance the needs of people with the needs of the environment. The states then allow municipalities to develop local ordinances and bylaws to meet land use goals. As local desires change, or as conflicting uses arise, local ordinances and bylaws may not be aligned with state planning goals. Educating and providing capacity support to local planners can advance the vision of aligning state and municipal goals and plans for ecosystem protection.

Because watersheds extend over political boundaries, watershed planning presents an opportunity to create plans that work on larger scales than individual municipal ordinances or bylaws. Each state supports watershed planning by developing plans for priority watershed areas and by providing assistance to independent groups wishing to develop plans. Watershed areas with published and accepted plans are eligible for implementation funding under Section 319 of the Clean Water Act; therefore, increasing the number of accepted plans is a priority.

As a regional partnership, NBEP supports planning at multiple scales by analyzing and communicating cross-boundary information, convening watershed-scale workgroups to develop tools and recommendations, and providing funding to support capacity-building as well as interstate projects that may not be eligible for state funding.

## Potential Projects

-   Foster adoption of Low Impact Development (LID) principles in local ordinances and bylaws.

-   Support development of Watershed Management Plans and Watershed-Based Plans.

-   Promote wider use and integration of existing land use tools and plans.

-   Create NBEP Science Updates and web applications to communicate information about impacts of land use change on water quality and wildlife habitats.

-   Conduct research and convene partners in workgroups to develop information and tools to inform land use policies for improved watershed management.

-   Seek funding to provide ongoing support for regional circuit-rider positions that lend capacity to local planners.

## Outputs

-   Ten additional watershed plans in Rhode Island [@ridem2024a]

-   More municipalities codifying Low Impact Development principles

-   NBEP Science Updates and tools

-   Workgroup products, including information and tools to inform land use policies

-   Sustained regional circuit-rider positions at state and regional planning agencies

## Outcomes

-   More watershed areas eligible for and seeking implementation funds for non-point source pollution projects

-   Better integration of land use planning protective of natural resources at various scales

## Indicators

Population, Land Use, Impervious Cover, Open Space

## NBEP role

Convene, Synthesize and communicate science, Fund capacity and projects

## Implementing Partners

RIDEM, MassDEP, RI Division of Statewide Planning, SRPEDD, OCPC, URI Coastal Institute, URI Cooperative Extension, NBNERR, Mass Audubon, ASRI, Save The Bay, SNEP Network, Blackstone Watershed Collaborative

## Location

Narragansett Bay region

## Timeline for Initiation

Ongoing

## Estimated costs/potential funding sources

\$10k–500k

NBEP 320/SNEP
