---
title: "Action Water-4.1: Trash and Marine Debris"
---

::: {.callout-info}
# Full Action Statement

Prevent and remove aquatic trash and marine debris.
:::

# Action Description and Statement of Need

This Action combines efforts to prevent the creation of trash at its source through education and regulation with its removal through technology and coordinated cleanups. Efforts can capitalize on regional plans to create action on preventing and removing trash and debris. Examples include NOAA’s 2024 Southern New England Marine Debris Action Plan and EPA’s Trash Free Waters Program.

Aquatic trash and marine debris harm water quality, endanger plants and animals, and degrade waterbodies that support recreation and tourism. Plastic is particularly problematic due to its ubiquitous presence, longevity, and tendency to break into smaller pieces [@fulfer2023]. Trash can also worsen flooding and disrupt wastewater operations by clogging waterways and infrastructure.

Outreach and education can motivate best practices for retailers and consumers to prevent trash from reaching waterways. Policies and legislation can also help reduce trash at its sources. For example, Connecticut, Rhode Island, and many municipalities in Massachusetts have single-use plastic bag bans. Policies to extend end-user responsibilities like “bottle bills” can facilitate recycling through a cash deposit system. Massachusetts and Connecticut operate bottle deposit systems and efforts are ongoing to establish a system in Rhode Island.

Dozens of organizations champion multifaceted efforts to remove trash and marine debris from the environment. For example, Save The Bay is the Rhode Island state coordinator for Ocean Conservancy’s International Coastal Cleanup, which engages partner organizations and volunteers to organize dozens of cleanups and document their findings. In 2024, Rhode Island launched a statewide “Litter-Free Rhode Island” initiative, providing micro-grants to support local cleanup efforts on land and in waterways [@ridem2024a]. The Commercial Fisheries Research Foundation (CFRF) developed a plan to remove abandoned fishing gear, or “ghost gear,” from coastal Rhode Island waters, including Narragansett Bay; in the first two years of plan implementation, fishermen trained to support the project removed over 10,000 pounds of gear. Beyond cleanup efforts, various interception technologies can work around the clock to remove trash, and there may be opportunities to strategically use them to greater benefit in the Narragansett Bay region.

NBEP will fund priority education, planning, and implementation activities.

# Potential Projects

-   Convene partners to develop materials to inform policies and legislation aimed at reducing aquatic trash and marine debris.

-   Conduct regional needs/feasibility assessment for trash collection solutions on outfalls, rivers, and streams, and support funding and capacity to implement priority solutions.

# Outputs

-   Materials developed to inform policy and legislation solutions to reduce aquatic trash and marine debris

-   Needs/feasibility assessment for trash collection solutions on outfalls, rivers, and streams

-   More trash collection solutions deployed

# Outcomes

-   Improved capacity to remove aquatic trash and marine debris

-   Reduced volume of aquatic trash and marine debris

# Indicators

Impervious Cover, Emerging Contaminants, Water Quality Condition for Aquatic Life, Water Quality Condition for Recreation

# NBEP role

Fund capacity and projects, Synthesize and communicate science

# Implementing Partners

EPA, NOAA, Save The Bay, Blackstone Watershed Collaborative, Taunton River Watershed Alliance, Commercial Fisheries Research Foundation, URI, RIRC, watershed associations

# Location

These actions will take place at specific sites, in neighborhoods, municipalities, watersheds, and local waterbodies.

# Timeline for initiation

2030-2032

# Estimated costs/potential funding sources

\$500K–1M

NBEP 320/SNEP, Municipal, state, EPA Trash-Free Waters, NOAA Marine Debris Program
