---
title: "Action Habitat-3.2: Salt Marsh Restoration"
---

::: callout-note
## Full Action Statement

Restore coastal wetlands and reconnect with uplands for habitat migration, wildlife, and recreation.
:::

## Action Description and Statement of Need

This Action will accelerate salt marsh restoration using techniques to restore marsh hydrology and upland connectivity and ensure resilience of these habitats and their associated wildlife to sea level rise. Sustaining salt marshes involves a variety of techniques to restore and enhance subsiding marshes and to conserve adjacent uplands for marshes to migrate inland as sea levels rise [@mckown2024].

The natural hydrology of tidal marshes has been impacted by agriculture, mosquito ditching, and other infrastructure that prevents water from draining from the marsh after rains and high tides. Impounded water causes native marsh plants adapted to drier conditions at low tide to die, resulting in subsidence of the marsh surface [@pappal2022]. Locally-pioneered restoration techniques involve digging shallow creeks or runnels to facilitate gradual water drainage and placing sediment to elevate degraded marshes to make them more resilient to sea level rise [@savethebay2021b]. These techniques have been used in several Rhode Island locations, including Succotash Marsh in South Kingstown where NBEP is funding the planning and design phases of a project managed by the Narragansett Bay National Estuarine Research Reserve.

Accelerating sea level rise is outpacing natural salt marsh accretion, causing marshes to erode and drown in place [@kutcher2018]. Marshes can migrate inland onto low-lying areas, but this process may be impeded by built structures, invasive species, or steep topography, among other barriers [@burman2023]. MA DER is funding tidal restriction prioritization and field assessment work in the Massachusetts portion of the Narragansett Bay region to identify priority barriers to marsh migration and aquatic connectivity. Partners must identify opportunities to conserve adjacent uplands in densely populated and urbanized areas for future inland marsh migration. Because most properties adjacent to salt marshes are privately owned, managed migration will involve a variety of land use changes, including land acquisition, redevelopment planning, rolling easements, and setback and buffer definitions. Proactive community engagement is therefore a crucial aspect of salt marsh resilience planning and implementation.

NBEP will continue to convene and coordinate partners across state and institutional boundaries to coordinate and share knowledge, practices, and outcomes of saltmarsh restoration projects in the Salt Marsh RAMP workgroup. NBEP will fund capacity for community outreach, planning, and implementation, and support partners by seeking external funding.

## Potential Projects

-   Sustain marshes in place with a suite of hydrology restoration techniques to address legacy human impacts.

-   Accelerate work to elevate priority subsiding marshes using sediment placement techniques.

-   Explore beneficial use of dredged material to help marshes keep up with rising seas or to restore areas of exposed sediment with high concentrations of contaminants.

-   Facilitate marsh migration through land conservation and managed retreat through land acquisition, redevelopment planning, rolling easements, setbacks, and buffer definitions.

-   Deliver ongoing one-on-one technical assistance to municipal parks and land use programs.

-   Identify tidal restriction restoration opportunities in concert with other restoration techniques.

-   Maintain the Salt Marsh RAMP workgroup project tool, MarshMap, and expand the tool to include Massachusetts and Connecticut projects.

## Outputs

-   Coordinated meetings for groups pursuing saltmarsh restoration

-   Annually updated list of priority saltmarsh restoration projects

-   New land use policy strategies adopted to accommodate marsh migration

## Outcomes

-   Federal, regional, state, NGO, and local partners coordinate to plan and implement restoration projects

-   Increased number of marsh restoration, enhancement, and marsh migration facilitation projects

-   More acres of saltmarsh restored

## Indicators

Sea Level, Land Use, Salt Marsh, Open Space

## NBEP role

Convene, Synthesize and communicate science, Fund capacity and projects

## Implementing Partners

EPA, NBNERR, RIDEM, Save The Bay, MA DER, NOAA, CRMC, USFWS, Mass Audubon

## Location

Coastal and riverine salt marshes

## Timeline for initiation

Ongoing

## Estimated costs/potential funding sources

\$10M+

NBEP 320/SNEP, NBEP BIL, EPA SNEP, MA DER
