---
title: "About the Narragansett Bay Region"
---

The Narragansett Bay region spans over 2,000 square miles of land comprising the watersheds of Narragansett Bay, Little Narragansett Bay, and the Coastal Salt Ponds. This landscape unites two million people across 113 cities and towns in Massachusetts, Rhode Island, and Connecticut. A mosaic of urban and suburban lands is surrounded by forested landscapes and networks of rivers and streams. Reaching inland more than 50 miles, the region’s watersheds have over 4,000 miles of rivers and streams and over 40,000 acres of lakes and ponds. Salty shores stretch along 700 miles of dunes, beaches, and rocky coasts. The region hosts diverse habitats, including roughly 4,300 acres of salt marsh habitat and 875 acres of seagrass habitat, that sustain wildlife, support regional economies, and provide recreational opportunities.

# Narragansett Bay Watershed

The Narragansett Bay watershed spans 1,705 square miles across Rhode Island and Massachusetts and includes the major tributaries of the Blackstone River, Taunton River, and Pawtuxet River that flow into the 196 square mile bay. In Narragansett Bay, salt marshes and seagrasses have declined considerably from historical extents. Fish communities are transitioning toward seasonal and mid-Atlantic species as Bay water temperatures rise. Storms have eroded Bay shorelines. Upland in the watershed, development pressure is a major stressor, causing loss of forested and wetland habitats, impacting wildlife and the health of inland and coastal waters. The watershed is fourteen percent impervious cover and half of rivers and streams are unhealthy for fish and wildlife due to excess nutrients, oxygen depletion, and other parameters (NBEP 2017). Thousands of barriers, including dams and improperly sized culverts, not only block migration for important diadromous fish populations, but also increase flood risk. These impacts are felt particularly in the urban areas of Providence, Worcester, Fall River, and Woonsocket, where increasingly intense rainfall events flood roads, homes, and businesses. Decades of efforts have dramatically reduced nutrient and bacteria pollution in the Bay, yet half of the estuarine waters are still unhealthy for fish and other aquatic life, with stormwater pollution driving the majority of impairments (NBEP 2017).

# Little Narragansett Bay Watershed

The Little Narragansett Bay watershed spans 317 square miles across western Rhode Island and southeastern Connecticut and includes the major tributaries of the Wood River and Pawcatuck River that flow into a 4.8 square mile estuary. Compared to the Narragansett Bay watershed, the Little Narragansett Bay watershed has one-fifth the population density and is more heavily forested and protected with conservation lands. The Barn Island Wildlife Management Area—the largest managed coastal habitat area in Connecticut—protects substantial areas of salt marsh, deciduous forest, and avian habitat. Only five percent of the watershed is impervious cover and over seventy percent of the assessed streams and rivers are fit for aquatic life (NBEP 2017). Increasingly, the major watershed stressor is development-driven changes in land use. Water quality impacts tend to be concentrated near these expanding developed areas. Within the bay proper, seagrasses remain scarce and shellfishing is prohibited due to water quality concerns.

# Coastal Salt Ponds Watersheds

The Coastal Salt Ponds watersheds span 56 square miles along the southern coast of Rhode Island, running from Point Judith in the east to Little Narragansett Bay in the west. The Rhode Island Coastal Salt Ponds—Judith Pond, Potter’s Pond, Cards Pond, Trustom Pond, Greenhill Pond, Ninigret Pond, Quonochontaug Pond, Winnapaug Pond, and Maschaug Pond—function as coastal estuarine lagoons connected to the ocean by inlets or breachways through barrier beaches. The ponds are shallow and brackish, which make them valuable as fish and shellfish nurseries but also susceptible to eutrophication and bacterial loading. Each pond has a unique identity and supports iconic wildlife and coastal habitats as well as many important commercial and recreational activities, including aquaculture. Pond assessments show 85% are fit for aquatic wildlife and 100% are fit for recreation (NBEP 2017). The long stretches of adjacent sandy beaches draw locals and visitors alike, making them important recreational and economic resources. Population size and development have grown across the salt ponds region in the last twenty years, though the population density is still only half that of the Narragansett Bay watershed. Rising sea levels and altered hydrology are major stressors for these unique coastal salt pond habitats causing erosion and subsidence that outpace marsh accretion.
